// <auto-generated />
using System;
using MamConnect.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MamConnect.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251105144406_AddChildAllergies")]
    partial class AddChildAllergies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChildUser", b =>
                {
                    b.Property<int>("ChildrenId")
                        .HasColumnType("int");

                    b.Property<int>("ParentsId")
                        .HasColumnType("int");

                    b.HasKey("ChildrenId", "ParentsId");

                    b.HasIndex("ParentsId");

                    b.ToTable("ParentChildren", (string)null);

                    b.HasData(
                        new
                        {
                            ChildrenId = 1,
                            ParentsId = 7
                        },
                        new
                        {
                            ChildrenId = 1,
                            ParentsId = 8
                        },
                        new
                        {
                            ChildrenId = 2,
                            ParentsId = 7
                        },
                        new
                        {
                            ChildrenId = 2,
                            ParentsId = 8
                        },
                        new
                        {
                            ChildrenId = 3,
                            ParentsId = 9
                        },
                        new
                        {
                            ChildrenId = 4,
                            ParentsId = 10
                        },
                        new
                        {
                            ChildrenId = 4,
                            ParentsId = 11
                        },
                        new
                        {
                            ChildrenId = 5,
                            ParentsId = 10
                        },
                        new
                        {
                            ChildrenId = 5,
                            ParentsId = 11
                        },
                        new
                        {
                            ChildrenId = 6,
                            ParentsId = 12
                        },
                        new
                        {
                            ChildrenId = 7,
                            ParentsId = 13
                        },
                        new
                        {
                            ChildrenId = 7,
                            ParentsId = 14
                        },
                        new
                        {
                            ChildrenId = 8,
                            ParentsId = 15
                        },
                        new
                        {
                            ChildrenId = 8,
                            ParentsId = 16
                        },
                        new
                        {
                            ChildrenId = 9,
                            ParentsId = 15
                        },
                        new
                        {
                            ChildrenId = 9,
                            ParentsId = 16
                        },
                        new
                        {
                            ChildrenId = 10,
                            ParentsId = 17
                        },
                        new
                        {
                            ChildrenId = 10,
                            ParentsId = 18
                        },
                        new
                        {
                            ChildrenId = 11,
                            ParentsId = 17
                        },
                        new
                        {
                            ChildrenId = 11,
                            ParentsId = 18
                        },
                        new
                        {
                            ChildrenId = 12,
                            ParentsId = 19
                        },
                        new
                        {
                            ChildrenId = 13,
                            ParentsId = 20
                        },
                        new
                        {
                            ChildrenId = 13,
                            ParentsId = 21
                        },
                        new
                        {
                            ChildrenId = 14,
                            ParentsId = 20
                        },
                        new
                        {
                            ChildrenId = 14,
                            ParentsId = 21
                        },
                        new
                        {
                            ChildrenId = 15,
                            ParentsId = 22
                        },
                        new
                        {
                            ChildrenId = 16,
                            ParentsId = 23
                        },
                        new
                        {
                            ChildrenId = 16,
                            ParentsId = 24
                        },
                        new
                        {
                            ChildrenId = 17,
                            ParentsId = 23
                        },
                        new
                        {
                            ChildrenId = 17,
                            ParentsId = 24
                        },
                        new
                        {
                            ChildrenId = 18,
                            ParentsId = 25
                        },
                        new
                        {
                            ChildrenId = 19,
                            ParentsId = 26
                        },
                        new
                        {
                            ChildrenId = 19,
                            ParentsId = 27
                        });
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("AssistantId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssistantId");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allergies = "Arachides",
                            AssistantId = 2,
                            BirthDate = new DateOnly(2019, 5, 21),
                            FirstName = "Liam",
                            LastName = "Durand"
                        },
                        new
                        {
                            Id = 2,
                            AssistantId = 2,
                            BirthDate = new DateOnly(2020, 3, 14),
                            FirstName = "Emma",
                            LastName = "Durand"
                        },
                        new
                        {
                            Id = 3,
                            Allergies = "Proteines de lait de vache",
                            AssistantId = 2,
                            BirthDate = new DateOnly(2020, 11, 2),
                            FirstName = "Noah",
                            LastName = "Martin"
                        },
                        new
                        {
                            Id = 4,
                            AssistantId = 3,
                            BirthDate = new DateOnly(2018, 7, 9),
                            FirstName = "Olivia",
                            LastName = "Lambert"
                        },
                        new
                        {
                            Id = 5,
                            AssistantId = 3,
                            BirthDate = new DateOnly(2019, 1, 30),
                            FirstName = "Ava",
                            LastName = "Lambert"
                        },
                        new
                        {
                            Id = 6,
                            Allergies = "Oeuf",
                            AssistantId = 3,
                            BirthDate = new DateOnly(2021, 4, 18),
                            FirstName = "Ethan",
                            LastName = "Bernard"
                        },
                        new
                        {
                            Id = 7,
                            AssistantId = 3,
                            BirthDate = new DateOnly(2020, 9, 5),
                            FirstName = "Mia",
                            LastName = "Lefevre"
                        },
                        new
                        {
                            Id = 8,
                            AssistantId = 4,
                            BirthDate = new DateOnly(2018, 12, 12),
                            FirstName = "Lucas",
                            LastName = "Petit"
                        },
                        new
                        {
                            Id = 9,
                            Allergies = "Pollen de bouleau",
                            AssistantId = 4,
                            BirthDate = new DateOnly(2019, 6, 22),
                            FirstName = "Sophia",
                            LastName = "Petit"
                        },
                        new
                        {
                            Id = 10,
                            AssistantId = 4,
                            BirthDate = new DateOnly(2020, 2, 11),
                            FirstName = "Mason",
                            LastName = "Moreau"
                        },
                        new
                        {
                            Id = 11,
                            AssistantId = 4,
                            BirthDate = new DateOnly(2018, 10, 3),
                            FirstName = "Isabella",
                            LastName = "Moreau"
                        },
                        new
                        {
                            Id = 12,
                            Allergies = "Fruits a coque",
                            AssistantId = 4,
                            BirthDate = new DateOnly(2021, 1, 27),
                            FirstName = "Harper",
                            LastName = "Garnier"
                        },
                        new
                        {
                            Id = 13,
                            AssistantId = 5,
                            BirthDate = new DateOnly(2019, 8, 15),
                            FirstName = "James",
                            LastName = "Robert"
                        },
                        new
                        {
                            Id = 14,
                            AssistantId = 5,
                            BirthDate = new DateOnly(2020, 5, 16),
                            FirstName = "Amelia",
                            LastName = "Robert"
                        },
                        new
                        {
                            Id = 15,
                            AssistantId = 5,
                            BirthDate = new DateOnly(2018, 4, 7),
                            FirstName = "Benjamin",
                            LastName = "Caron"
                        },
                        new
                        {
                            Id = 16,
                            Allergies = "Latex",
                            AssistantId = 6,
                            BirthDate = new DateOnly(2019, 12, 1),
                            FirstName = "Charlotte",
                            LastName = "Marchand"
                        },
                        new
                        {
                            Id = 17,
                            AssistantId = 6,
                            BirthDate = new DateOnly(2020, 7, 19),
                            FirstName = "Elijah",
                            LastName = "Marchand"
                        },
                        new
                        {
                            Id = 18,
                            AssistantId = 6,
                            BirthDate = new DateOnly(2021, 9, 23),
                            FirstName = "Evelyn",
                            LastName = "Dupont"
                        },
                        new
                        {
                            Id = 19,
                            AssistantId = 6,
                            BirthDate = new DateOnly(2018, 3, 13),
                            FirstName = "Henry",
                            LastName = "Renard"
                        });
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.ChildVaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AdministrationDate")
                        .HasColumnType("date");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VaccineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VaccineId");

                    b.HasIndex("ChildId", "VaccineId", "ScheduledDate")
                        .IsUnique()
                        .HasFilter("[ScheduledDate] IS NOT NULL");

                    b.ToTable("ChildVaccines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdministrationDate = new DateOnly(2019, 7, 21),
                            ChildId = 1,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 7, 21),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 2,
                            AdministrationDate = new DateOnly(2019, 9, 21),
                            ChildId = 1,
                            Comments = "Dose réalisée lors de la visite mensuelle.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 9, 21),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 3,
                            ChildId = 1,
                            Comments = "Rappel prévu lors de la prochaine visite médicale.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 5, 21),
                            Status = 2,
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 4,
                            AdministrationDate = new DateOnly(2020, 5, 14),
                            ChildId = 2,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 5, 14),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 5,
                            ChildId = 2,
                            Comments = "Dose programmée avec la famille.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 7, 14),
                            Status = 2,
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 6,
                            ChildId = 2,
                            Comments = "Rappel prévu lors de la prochaine visite médicale.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 3, 14),
                            Status = 2,
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 7,
                            AdministrationDate = new DateOnly(2021, 1, 2),
                            ChildId = 3,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 1, 2),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 8,
                            AdministrationDate = new DateOnly(2021, 3, 2),
                            ChildId = 3,
                            Comments = "Dose réalisée lors de la visite mensuelle.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 3, 2),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 9,
                            ChildId = 3,
                            Comments = "Relance nécessaire auprès des parents.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 11, 2),
                            Status = 3,
                            UpdatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 10,
                            AdministrationDate = new DateOnly(2018, 9, 9),
                            ChildId = 4,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2018, 9, 9),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 11,
                            ChildId = 4,
                            Comments = "Dose programmée avec la famille.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2018, 11, 9),
                            Status = 2,
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 12,
                            ChildId = 4,
                            Comments = "Rappel prévu lors de la prochaine visite médicale.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 7, 9),
                            Status = 2,
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 13,
                            AdministrationDate = new DateOnly(2019, 3, 30),
                            ChildId = 5,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 3, 30),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 14,
                            AdministrationDate = new DateOnly(2019, 5, 30),
                            ChildId = 5,
                            Comments = "Dose réalisée lors de la visite mensuelle.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 5, 30),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 15,
                            ChildId = 5,
                            Comments = "Rappel prévu lors de la prochaine visite médicale.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 1, 30),
                            Status = 2,
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 16,
                            AdministrationDate = new DateOnly(2021, 6, 18),
                            ChildId = 6,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 6, 18),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 17,
                            ChildId = 6,
                            Comments = "Dose programmée avec la famille.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 8, 18),
                            Status = 2,
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 18,
                            ChildId = 6,
                            Comments = "Relance nécessaire auprès des parents.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2022, 4, 18),
                            Status = 3,
                            UpdatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 19,
                            AdministrationDate = new DateOnly(2020, 11, 5),
                            ChildId = 7,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 11, 5),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 20,
                            AdministrationDate = new DateOnly(2021, 1, 5),
                            ChildId = 7,
                            Comments = "Dose réalisée lors de la visite mensuelle.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 1, 5),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 21,
                            ChildId = 7,
                            Comments = "Rappel prévu lors de la prochaine visite médicale.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 9, 5),
                            Status = 2,
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 22,
                            AdministrationDate = new DateOnly(2019, 2, 12),
                            ChildId = 8,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 2, 12),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 23,
                            ChildId = 8,
                            Comments = "Dose programmée avec la famille.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 4, 12),
                            Status = 2,
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 24,
                            ChildId = 8,
                            Comments = "Rappel prévu lors de la prochaine visite médicale.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 12, 12),
                            Status = 2,
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 25,
                            AdministrationDate = new DateOnly(2019, 8, 22),
                            ChildId = 9,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 8, 22),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 26,
                            AdministrationDate = new DateOnly(2019, 10, 22),
                            ChildId = 9,
                            Comments = "Dose réalisée lors de la visite mensuelle.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 10, 22),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 27,
                            ChildId = 9,
                            Comments = "Relance nécessaire auprès des parents.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 6, 22),
                            Status = 3,
                            UpdatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 28,
                            AdministrationDate = new DateOnly(2020, 4, 11),
                            ChildId = 10,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 4, 11),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 29,
                            ChildId = 10,
                            Comments = "Dose programmée avec la famille.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 6, 11),
                            Status = 2,
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 30,
                            ChildId = 10,
                            Comments = "Rappel prévu lors de la prochaine visite médicale.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 2, 11),
                            Status = 2,
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 31,
                            AdministrationDate = new DateOnly(2018, 12, 3),
                            ChildId = 11,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2018, 12, 3),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 32,
                            AdministrationDate = new DateOnly(2019, 2, 3),
                            ChildId = 11,
                            Comments = "Dose réalisée lors de la visite mensuelle.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 2, 3),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 33,
                            ChildId = 11,
                            Comments = "Rappel prévu lors de la prochaine visite médicale.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 10, 3),
                            Status = 2,
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 34,
                            AdministrationDate = new DateOnly(2021, 3, 27),
                            ChildId = 12,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 3, 27),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 35,
                            ChildId = 12,
                            Comments = "Dose programmée avec la famille.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 5, 27),
                            Status = 2,
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 36,
                            ChildId = 12,
                            Comments = "Relance nécessaire auprès des parents.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2022, 1, 27),
                            Status = 3,
                            UpdatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 37,
                            AdministrationDate = new DateOnly(2019, 10, 15),
                            ChildId = 13,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 10, 15),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 38,
                            AdministrationDate = new DateOnly(2019, 12, 15),
                            ChildId = 13,
                            Comments = "Dose réalisée lors de la visite mensuelle.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 12, 15),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 39,
                            ChildId = 13,
                            Comments = "Rappel prévu lors de la prochaine visite médicale.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 8, 15),
                            Status = 2,
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 40,
                            AdministrationDate = new DateOnly(2020, 7, 16),
                            ChildId = 14,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 7, 16),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 41,
                            ChildId = 14,
                            Comments = "Dose programmée avec la famille.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 9, 16),
                            Status = 2,
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 42,
                            ChildId = 14,
                            Comments = "Rappel prévu lors de la prochaine visite médicale.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 5, 16),
                            Status = 2,
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 43,
                            AdministrationDate = new DateOnly(2018, 6, 7),
                            ChildId = 15,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2018, 6, 7),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 44,
                            AdministrationDate = new DateOnly(2018, 8, 7),
                            ChildId = 15,
                            Comments = "Dose réalisée lors de la visite mensuelle.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2018, 8, 7),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 45,
                            ChildId = 15,
                            Comments = "Relance nécessaire auprès des parents.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 4, 7),
                            Status = 3,
                            UpdatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 46,
                            AdministrationDate = new DateOnly(2020, 2, 1),
                            ChildId = 16,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 2, 1),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 47,
                            ChildId = 16,
                            Comments = "Dose programmée avec la famille.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 4, 1),
                            Status = 2,
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 48,
                            ChildId = 16,
                            Comments = "Rappel prévu lors de la prochaine visite médicale.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 12, 1),
                            Status = 2,
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 49,
                            AdministrationDate = new DateOnly(2020, 9, 19),
                            ChildId = 17,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 9, 19),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 50,
                            AdministrationDate = new DateOnly(2020, 11, 19),
                            ChildId = 17,
                            Comments = "Dose réalisée lors de la visite mensuelle.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2020, 11, 19),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 51,
                            ChildId = 17,
                            Comments = "Rappel prévu lors de la prochaine visite médicale.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 7, 19),
                            Status = 2,
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 52,
                            AdministrationDate = new DateOnly(2021, 11, 23),
                            ChildId = 18,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2021, 11, 23),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 53,
                            ChildId = 18,
                            Comments = "Dose programmée avec la famille.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2022, 1, 23),
                            Status = 2,
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 54,
                            ChildId = 18,
                            Comments = "Relance nécessaire auprès des parents.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2022, 9, 23),
                            Status = 3,
                            UpdatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 55,
                            AdministrationDate = new DateOnly(2018, 5, 13),
                            ChildId = 19,
                            Comments = "Dose initiale administrée conformément au calendrier.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2018, 5, 13),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 56,
                            AdministrationDate = new DateOnly(2018, 7, 13),
                            ChildId = 19,
                            Comments = "Dose réalisée lors de la visite mensuelle.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2018, 7, 13),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 57,
                            ChildId = 19,
                            Comments = "Rappel prévu lors de la prochaine visite médicale.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledDate = new DateOnly(2019, 3, 13),
                            Status = 2,
                            VaccineId = 13
                        });
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.DailyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("DailyReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChildId = 1,
                            Content = "First report Liam",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ChildId = 2,
                            Content = "First report Emma",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = "AQAAAAEAACcQAAAAEBpXW/zlBa5UwW0tpsWsFmvZSK4bsEq+aPNbw+GQYlS2C/Zx6ujWmAoBrtWEDegbPA==",
                            PhoneNumber = "0123456789",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "assistant1@example.com",
                            FirstName = "Alice",
                            LastName = "Martin",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0100000001",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "assistant2@example.com",
                            FirstName = "Bruno",
                            LastName = "Petit",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0100000002",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "assistant3@example.com",
                            FirstName = "Claire",
                            LastName = "Leroy",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0100000003",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "assistant4@example.com",
                            FirstName = "David",
                            LastName = "Morel",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0100000004",
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "assistant5@example.com",
                            FirstName = "Emma",
                            LastName = "Roussel",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0100000005",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            Email = "parent1@example.com",
                            FirstName = "Paul",
                            LastName = "Durand",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000001",
                            Role = 0
                        },
                        new
                        {
                            Id = 8,
                            Email = "parent2@example.com",
                            FirstName = "Claire",
                            LastName = "Durand",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000002",
                            Role = 0
                        },
                        new
                        {
                            Id = 9,
                            Email = "parent3@example.com",
                            FirstName = "Sophie",
                            LastName = "Martin",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000003",
                            Role = 0
                        },
                        new
                        {
                            Id = 10,
                            Email = "parent4@example.com",
                            FirstName = "Julien",
                            LastName = "Lambert",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000004",
                            Role = 0
                        },
                        new
                        {
                            Id = 11,
                            Email = "parent5@example.com",
                            FirstName = "Camille",
                            LastName = "Lambert",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000005",
                            Role = 0
                        },
                        new
                        {
                            Id = 12,
                            Email = "parent6@example.com",
                            FirstName = "Nadia",
                            LastName = "Bernard",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000006",
                            Role = 0
                        },
                        new
                        {
                            Id = 13,
                            Email = "parent7@example.com",
                            FirstName = "Hugo",
                            LastName = "Lefevre",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000007",
                            Role = 0
                        },
                        new
                        {
                            Id = 14,
                            Email = "parent8@example.com",
                            FirstName = "Elise",
                            LastName = "Lefevre",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000008",
                            Role = 0
                        },
                        new
                        {
                            Id = 15,
                            Email = "parent9@example.com",
                            FirstName = "Thomas",
                            LastName = "Petit",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000009",
                            Role = 0
                        },
                        new
                        {
                            Id = 16,
                            Email = "parent10@example.com",
                            FirstName = "Laura",
                            LastName = "Petit",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000010",
                            Role = 0
                        },
                        new
                        {
                            Id = 17,
                            Email = "parent11@example.com",
                            FirstName = "Antoine",
                            LastName = "Moreau",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000011",
                            Role = 0
                        },
                        new
                        {
                            Id = 18,
                            Email = "parent12@example.com",
                            FirstName = "Marie",
                            LastName = "Moreau",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000012",
                            Role = 0
                        },
                        new
                        {
                            Id = 19,
                            Email = "parent13@example.com",
                            FirstName = "Isabelle",
                            LastName = "Garnier",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000013",
                            Role = 0
                        },
                        new
                        {
                            Id = 20,
                            Email = "parent14@example.com",
                            FirstName = "Victor",
                            LastName = "Robert",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000014",
                            Role = 0
                        },
                        new
                        {
                            Id = 21,
                            Email = "parent15@example.com",
                            FirstName = "Amelie",
                            LastName = "Robert",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000015",
                            Role = 0
                        },
                        new
                        {
                            Id = 22,
                            Email = "parent16@example.com",
                            FirstName = "Patrick",
                            LastName = "Caron",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000016",
                            Role = 0
                        },
                        new
                        {
                            Id = 23,
                            Email = "parent17@example.com",
                            FirstName = "Helene",
                            LastName = "Marchand",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000017",
                            Role = 0
                        },
                        new
                        {
                            Id = 24,
                            Email = "parent18@example.com",
                            FirstName = "Xavier",
                            LastName = "Marchand",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000018",
                            Role = 0
                        },
                        new
                        {
                            Id = 25,
                            Email = "parent19@example.com",
                            FirstName = "Chantal",
                            LastName = "Dupont",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000019",
                            Role = 0
                        },
                        new
                        {
                            Id = 26,
                            Email = "parent20@example.com",
                            FirstName = "Olivier",
                            LastName = "Renard",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000020",
                            Role = 0
                        },
                        new
                        {
                            Id = 27,
                            Email = "parent21@example.com",
                            FirstName = "Lucie",
                            LastName = "Renard",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000021",
                            Role = 0
                        });
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vaccines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeInMonths = 2,
                            Name = "DTP et Coqueluche"
                        },
                        new
                        {
                            Id = 2,
                            AgeInMonths = 4,
                            Name = "DTP et Coqueluche"
                        },
                        new
                        {
                            Id = 3,
                            AgeInMonths = 11,
                            Name = "DTP et Coqueluche"
                        },
                        new
                        {
                            Id = 4,
                            AgeInMonths = 2,
                            Name = "Hib"
                        },
                        new
                        {
                            Id = 5,
                            AgeInMonths = 4,
                            Name = "Hib"
                        },
                        new
                        {
                            Id = 6,
                            AgeInMonths = 11,
                            Name = "Hib"
                        },
                        new
                        {
                            Id = 7,
                            AgeInMonths = 2,
                            Name = "Hépatite B"
                        },
                        new
                        {
                            Id = 8,
                            AgeInMonths = 4,
                            Name = "Hépatite B"
                        },
                        new
                        {
                            Id = 9,
                            AgeInMonths = 11,
                            Name = "Hépatite B"
                        },
                        new
                        {
                            Id = 10,
                            AgeInMonths = 2,
                            Name = "Pneumocoque"
                        },
                        new
                        {
                            Id = 11,
                            AgeInMonths = 4,
                            Name = "Pneumocoque"
                        },
                        new
                        {
                            Id = 12,
                            AgeInMonths = 11,
                            Name = "Pneumocoque"
                        },
                        new
                        {
                            Id = 13,
                            AgeInMonths = 12,
                            Name = "ROR"
                        },
                        new
                        {
                            Id = 14,
                            AgeInMonths = 16,
                            Name = "ROR"
                        },
                        new
                        {
                            Id = 15,
                            AgeInMonths = 6,
                            Name = "Méningocoques ACWY"
                        },
                        new
                        {
                            Id = 16,
                            AgeInMonths = 12,
                            Name = "Méningocoques ACWY"
                        },
                        new
                        {
                            Id = 17,
                            AgeInMonths = 3,
                            Name = "Méningocoque B"
                        },
                        new
                        {
                            Id = 18,
                            AgeInMonths = 5,
                            Name = "Méningocoque B"
                        },
                        new
                        {
                            Id = 19,
                            AgeInMonths = 12,
                            Name = "Méningocoque B"
                        });
                });

            modelBuilder.Entity("ChildUser", b =>
                {
                    b.HasOne("MamConnect.Domain.Entities.Child", null)
                        .WithMany()
                        .HasForeignKey("ChildrenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MamConnect.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ParentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.Child", b =>
                {
                    b.HasOne("MamConnect.Domain.Entities.User", "Assistant")
                        .WithMany("AssignedChildren")
                        .HasForeignKey("AssistantId");

                    b.Navigation("Assistant");
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.ChildVaccine", b =>
                {
                    b.HasOne("MamConnect.Domain.Entities.Child", "Child")
                        .WithMany("ChildVaccines")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MamConnect.Domain.Entities.Vaccine", "Vaccine")
                        .WithMany("ChildVaccines")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.DailyReport", b =>
                {
                    b.HasOne("MamConnect.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.Child", b =>
                {
                    b.Navigation("ChildVaccines");
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedChildren");
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.Vaccine", b =>
                {
                    b.Navigation("ChildVaccines");
                });
#pragma warning restore 612, 618
        }
    }
}
