// <auto-generated />
using System;
using MamConnect.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MamConnect.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250910134537_NomMigration")]
    partial class NomMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChildUser", b =>
                {
                    b.Property<int>("ChildrenId")
                        .HasColumnType("int");

                    b.Property<int>("ParentsId")
                        .HasColumnType("int");

                    b.HasKey("ChildrenId", "ParentsId");

                    b.HasIndex("ParentsId");

                    b.ToTable("ParentChildren", (string)null);

                    b.HasData(
                        new
                        {
                            ChildrenId = 1,
                            ParentsId = 3
                        },
                        new
                        {
                            ChildrenId = 2,
                            ParentsId = 4
                        });
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssistantId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssistantId");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssistantId = 1,
                            BirthDate = new DateOnly(2020, 1, 1),
                            FirstName = "Emeline"
                        },
                        new
                        {
                            Id = 2,
                            AssistantId = 2,
                            BirthDate = new DateOnly(2020, 1, 1),
                            FirstName = "Alice"
                        });
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.DailyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("DailyReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChildId = 1,
                            Content = "First report Emeline",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ChildId = 2,
                            Content = "First report Alice",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            Role = 0
                        });
                });

            modelBuilder.Entity("ChildUser", b =>
                {
                    b.HasOne("MamConnect.Domain.Entities.Child", null)
                        .WithMany()
                        .HasForeignKey("ChildrenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MamConnect.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ParentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.Child", b =>
                {
                    b.HasOne("MamConnect.Domain.Entities.User", "Assistant")
                        .WithMany("AssignedChildren")
                        .HasForeignKey("AssistantId");

                    b.Navigation("Assistant");
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.DailyReport", b =>
                {
                    b.HasOne("MamConnect.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedChildren");
                });
#pragma warning restore 612, 618
        }
    }
}
