// <auto-generated />
using System;
using MamConnect.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MamConnect.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChildUser", b =>
                {
                    b.Property<int>("ChildrenId")
                        .HasColumnType("int");

                    b.Property<int>("ParentsId")
                        .HasColumnType("int");

                    b.HasKey("ChildrenId", "ParentsId");

                    b.HasIndex("ParentsId");

                    b.ToTable("ParentChildren", (string)null);

                    b.HasData(
                        new
                        {
                            ChildrenId = 1,
                            ParentsId = 7
                        },
                        new
                        {
                            ChildrenId = 1,
                            ParentsId = 8
                        },
                        new
                        {
                            ChildrenId = 2,
                            ParentsId = 7
                        },
                        new
                        {
                            ChildrenId = 2,
                            ParentsId = 8
                        },
                        new
                        {
                            ChildrenId = 3,
                            ParentsId = 9
                        },
                        new
                        {
                            ChildrenId = 4,
                            ParentsId = 10
                        },
                        new
                        {
                            ChildrenId = 4,
                            ParentsId = 11
                        },
                        new
                        {
                            ChildrenId = 5,
                            ParentsId = 10
                        },
                        new
                        {
                            ChildrenId = 5,
                            ParentsId = 11
                        },
                        new
                        {
                            ChildrenId = 6,
                            ParentsId = 12
                        },
                        new
                        {
                            ChildrenId = 7,
                            ParentsId = 13
                        },
                        new
                        {
                            ChildrenId = 7,
                            ParentsId = 14
                        },
                        new
                        {
                            ChildrenId = 8,
                            ParentsId = 15
                        },
                        new
                        {
                            ChildrenId = 8,
                            ParentsId = 16
                        },
                        new
                        {
                            ChildrenId = 9,
                            ParentsId = 15
                        },
                        new
                        {
                            ChildrenId = 9,
                            ParentsId = 16
                        },
                        new
                        {
                            ChildrenId = 10,
                            ParentsId = 17
                        },
                        new
                        {
                            ChildrenId = 10,
                            ParentsId = 18
                        },
                        new
                        {
                            ChildrenId = 11,
                            ParentsId = 17
                        },
                        new
                        {
                            ChildrenId = 11,
                            ParentsId = 18
                        },
                        new
                        {
                            ChildrenId = 12,
                            ParentsId = 19
                        },
                        new
                        {
                            ChildrenId = 13,
                            ParentsId = 20
                        },
                        new
                        {
                            ChildrenId = 13,
                            ParentsId = 21
                        },
                        new
                        {
                            ChildrenId = 14,
                            ParentsId = 20
                        },
                        new
                        {
                            ChildrenId = 14,
                            ParentsId = 21
                        },
                        new
                        {
                            ChildrenId = 15,
                            ParentsId = 22
                        },
                        new
                        {
                            ChildrenId = 16,
                            ParentsId = 23
                        },
                        new
                        {
                            ChildrenId = 16,
                            ParentsId = 24
                        },
                        new
                        {
                            ChildrenId = 17,
                            ParentsId = 23
                        },
                        new
                        {
                            ChildrenId = 17,
                            ParentsId = 24
                        },
                        new
                        {
                            ChildrenId = 18,
                            ParentsId = 25
                        },
                        new
                        {
                            ChildrenId = 19,
                            ParentsId = 26
                        },
                        new
                        {
                            ChildrenId = 19,
                            ParentsId = 27
                        });
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssistantId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssistantId");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssistantId = 2,
                            BirthDate = new DateOnly(2019, 5, 21),
                            FirstName = "Liam"
                        },
                        new
                        {
                            Id = 2,
                            AssistantId = 2,
                            BirthDate = new DateOnly(2020, 3, 14),
                            FirstName = "Emma"
                        },
                        new
                        {
                            Id = 3,
                            AssistantId = 2,
                            BirthDate = new DateOnly(2020, 11, 2),
                            FirstName = "Noah"
                        },
                        new
                        {
                            Id = 4,
                            AssistantId = 3,
                            BirthDate = new DateOnly(2018, 7, 9),
                            FirstName = "Olivia"
                        },
                        new
                        {
                            Id = 5,
                            AssistantId = 3,
                            BirthDate = new DateOnly(2019, 1, 30),
                            FirstName = "Ava"
                        },
                        new
                        {
                            Id = 6,
                            AssistantId = 3,
                            BirthDate = new DateOnly(2021, 4, 18),
                            FirstName = "Ethan"
                        },
                        new
                        {
                            Id = 7,
                            AssistantId = 3,
                            BirthDate = new DateOnly(2020, 9, 5),
                            FirstName = "Mia"
                        },
                        new
                        {
                            Id = 8,
                            AssistantId = 4,
                            BirthDate = new DateOnly(2018, 12, 12),
                            FirstName = "Lucas"
                        },
                        new
                        {
                            Id = 9,
                            AssistantId = 4,
                            BirthDate = new DateOnly(2019, 6, 22),
                            FirstName = "Sophia"
                        },
                        new
                        {
                            Id = 10,
                            AssistantId = 4,
                            BirthDate = new DateOnly(2020, 2, 11),
                            FirstName = "Mason"
                        },
                        new
                        {
                            Id = 11,
                            AssistantId = 4,
                            BirthDate = new DateOnly(2018, 10, 3),
                            FirstName = "Isabella"
                        },
                        new
                        {
                            Id = 12,
                            AssistantId = 4,
                            BirthDate = new DateOnly(2021, 1, 27),
                            FirstName = "Harper"
                        },
                        new
                        {
                            Id = 13,
                            AssistantId = 5,
                            BirthDate = new DateOnly(2019, 8, 15),
                            FirstName = "James"
                        },
                        new
                        {
                            Id = 14,
                            AssistantId = 5,
                            BirthDate = new DateOnly(2020, 5, 16),
                            FirstName = "Amelia"
                        },
                        new
                        {
                            Id = 15,
                            AssistantId = 5,
                            BirthDate = new DateOnly(2018, 4, 7),
                            FirstName = "Benjamin"
                        },
                        new
                        {
                            Id = 16,
                            AssistantId = 6,
                            BirthDate = new DateOnly(2019, 12, 1),
                            FirstName = "Charlotte"
                        },
                        new
                        {
                            Id = 17,
                            AssistantId = 6,
                            BirthDate = new DateOnly(2020, 7, 19),
                            FirstName = "Elijah"
                        },
                        new
                        {
                            Id = 18,
                            AssistantId = 6,
                            BirthDate = new DateOnly(2021, 9, 23),
                            FirstName = "Evelyn"
                        },
                        new
                        {
                            Id = 19,
                            AssistantId = 6,
                            BirthDate = new DateOnly(2018, 3, 13),
                            FirstName = "Henry"
                        });
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.DailyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("DailyReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChildId = 1,
                            Content = "First report Liam",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ChildId = 2,
                            Content = "First report Emma",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = "AQAAAAEAACcQAAAAEBpXW/zlBa5UwW0tpsWsFmvZSK4bsEq+aPNbw+GQYlS2C/Zx6ujWmAoBrtWEDegbPA==",
                            PhoneNumber = "0123456789",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "assistant1@example.com",
                            FirstName = "Alice",
                            LastName = "Martin",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0100000001",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "assistant2@example.com",
                            FirstName = "Bruno",
                            LastName = "Petit",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0100000002",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "assistant3@example.com",
                            FirstName = "Claire",
                            LastName = "Leroy",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0100000003",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "assistant4@example.com",
                            FirstName = "David",
                            LastName = "Morel",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0100000004",
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "assistant5@example.com",
                            FirstName = "Emma",
                            LastName = "Roussel",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0100000005",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            Email = "parent1@example.com",
                            FirstName = "Paul",
                            LastName = "Durand",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000001",
                            Role = 0
                        },
                        new
                        {
                            Id = 8,
                            Email = "parent2@example.com",
                            FirstName = "Claire",
                            LastName = "Durand",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000002",
                            Role = 0
                        },
                        new
                        {
                            Id = 9,
                            Email = "parent3@example.com",
                            FirstName = "Sophie",
                            LastName = "Martin",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000003",
                            Role = 0
                        },
                        new
                        {
                            Id = 10,
                            Email = "parent4@example.com",
                            FirstName = "Julien",
                            LastName = "Lambert",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000004",
                            Role = 0
                        },
                        new
                        {
                            Id = 11,
                            Email = "parent5@example.com",
                            FirstName = "Camille",
                            LastName = "Lambert",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000005",
                            Role = 0
                        },
                        new
                        {
                            Id = 12,
                            Email = "parent6@example.com",
                            FirstName = "Nadia",
                            LastName = "Bernard",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000006",
                            Role = 0
                        },
                        new
                        {
                            Id = 13,
                            Email = "parent7@example.com",
                            FirstName = "Hugo",
                            LastName = "Lefevre",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000007",
                            Role = 0
                        },
                        new
                        {
                            Id = 14,
                            Email = "parent8@example.com",
                            FirstName = "Elise",
                            LastName = "Lefevre",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000008",
                            Role = 0
                        },
                        new
                        {
                            Id = 15,
                            Email = "parent9@example.com",
                            FirstName = "Thomas",
                            LastName = "Petit",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000009",
                            Role = 0
                        },
                        new
                        {
                            Id = 16,
                            Email = "parent10@example.com",
                            FirstName = "Laura",
                            LastName = "Petit",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000010",
                            Role = 0
                        },
                        new
                        {
                            Id = 17,
                            Email = "parent11@example.com",
                            FirstName = "Antoine",
                            LastName = "Moreau",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000011",
                            Role = 0
                        },
                        new
                        {
                            Id = 18,
                            Email = "parent12@example.com",
                            FirstName = "Marie",
                            LastName = "Moreau",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000012",
                            Role = 0
                        },
                        new
                        {
                            Id = 19,
                            Email = "parent13@example.com",
                            FirstName = "Isabelle",
                            LastName = "Garnier",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000013",
                            Role = 0
                        },
                        new
                        {
                            Id = 20,
                            Email = "parent14@example.com",
                            FirstName = "Victor",
                            LastName = "Robert",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000014",
                            Role = 0
                        },
                        new
                        {
                            Id = 21,
                            Email = "parent15@example.com",
                            FirstName = "Amelie",
                            LastName = "Robert",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000015",
                            Role = 0
                        },
                        new
                        {
                            Id = 22,
                            Email = "parent16@example.com",
                            FirstName = "Patrick",
                            LastName = "Caron",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000016",
                            Role = 0
                        },
                        new
                        {
                            Id = 23,
                            Email = "parent17@example.com",
                            FirstName = "Helene",
                            LastName = "Marchand",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000017",
                            Role = 0
                        },
                        new
                        {
                            Id = 24,
                            Email = "parent18@example.com",
                            FirstName = "Xavier",
                            LastName = "Marchand",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000018",
                            Role = 0
                        },
                        new
                        {
                            Id = 25,
                            Email = "parent19@example.com",
                            FirstName = "Chantal",
                            LastName = "Dupont",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000019",
                            Role = 0
                        },
                        new
                        {
                            Id = 26,
                            Email = "parent20@example.com",
                            FirstName = "Olivier",
                            LastName = "Renard",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000020",
                            Role = 0
                        },
                        new
                        {
                            Id = 27,
                            Email = "parent21@example.com",
                            FirstName = "Lucie",
                            LastName = "Renard",
                            PasswordHash = "a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "0200000021",
                            Role = 0
                        });
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgesInMonths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vaccines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgesInMonths = "2,4,11",
                            Name = "DTP et Coqueluche"
                        },
                        new
                        {
                            Id = 2,
                            AgesInMonths = "2,4,11",
                            Name = "Hib"
                        },
                        new
                        {
                            Id = 3,
                            AgesInMonths = "2,4,11",
                            Name = "Hépatite B"
                        },
                        new
                        {
                            Id = 4,
                            AgesInMonths = "2,4,11",
                            Name = "Pneumocoque"
                        },
                        new
                        {
                            Id = 5,
                            AgesInMonths = "12,16",
                            Name = "ROR"
                        },
                        new
                        {
                            Id = 6,
                            AgesInMonths = "6,12",
                            Name = "Méningocoques ACWY"
                        },
                        new
                        {
                            Id = 7,
                            AgesInMonths = "3,5,12",
                            Name = "Méningocoque B"
                        });
                });

            modelBuilder.Entity("ChildUser", b =>
                {
                    b.HasOne("MamConnect.Domain.Entities.Child", null)
                        .WithMany()
                        .HasForeignKey("ChildrenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MamConnect.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ParentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.Child", b =>
                {
                    b.HasOne("MamConnect.Domain.Entities.User", "Assistant")
                        .WithMany("AssignedChildren")
                        .HasForeignKey("AssistantId");

                    b.Navigation("Assistant");
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.DailyReport", b =>
                {
                    b.HasOne("MamConnect.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MamConnect.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedChildren");
                });
#pragma warning restore 612, 618
        }
    }
}
