name: Build and Lint (MamConnect)

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: 🧩 Build .NET Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore MamConnect.sln

      - name: Build solution
        run: dotnet build MamConnect.sln --configuration Release --no-restore

      - name: Run tests (if any)
        run: dotnet test MamConnect.sln --no-build --verbosity normal
        continue-on-error: true

  frontend:
    name: ⚡ Lint Frontend (React)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint
